server:
  port: 8081
  servlet:
    context-path: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: false
spring:
  application:
    name: sf-registry-server