server:
  port: 8083
  servlet:
    context-path: /
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
spring:
  application:
    name: sf-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: sf-user-center
        uri: lb://sf-user-center
        predicates:
        - Path=/user-center/**